services:
  - type: web
    name: spotify-tunes-now
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn spotify_service:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 