// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wudfqvwsucezcvsuujlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZGZxdndzdWNlemN2c3V1amx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDEzMzAsImV4cCI6MjA2NTU3NzMzMH0.DtLssFCden9Y4fShvgkF_g8bhsuz4jVp0QM5MBtT0Sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);